kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: Court-Admin-Scheduling
    app-group: app-image
    name: {{ .Values.nameOverride }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: '{{ .Values.nameOverride }}:latest'
  resources: 
    {{- toYaml .Values.buildResources | nindent 4 }}
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    type: Dockerfile
    dockerfile: >-
      FROM
      image-registry.openshift-image-registry.svc:5000/ac1cc8-tools/web-artifacts
      as source

      FROM
      image-registry.openshift-image-registry.svc:5000/ac1cc8-tools/web-runtime
      as source


      # Copy the client application artifacts into the image ...

      COPY --from=source /opt/app-root/src/dist/. /tmp/app/dist/


      # Since the runtime image is itself an s2i image we need to

      # short circuit the s2i lifecycle.

      # The runtime image "loses" its s2i runtime voodoo when it

      # is used in a dockerStrategy, which is why the explicity 'CMD' is necessary

      CMD /usr/libexec/s2i/run
  triggers:
    - type: ConfigChange
  runPolicy: Serial
