apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIp }}
  ipFamilies:
    - IPv4
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  clusterIPs:
    - {{ .Values.service.clusterIp }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
