kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.licensePlate }}-dev
  labels:
    app: Court-Admin-Scheduling
    app-group: cas
    env: {{ .Values.environment }}
    name: {{ .Values.nameOverride }}
    role: {{ .Values.nameOverride }}
spec:
  host: court-admin-scheduling-dev.emerald.devops.bcgov
  to:
    kind: Service
    name: {{ .Values.nameOverride }}
    weight: 100
  port: 
    targetPort: {{ .Values.service.port }}-tcp
  tls: 
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None