apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIp }}
  ipFamilies:
    - IPv4
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  clusterIPs:
    - {{ .Values.service.clusterIp }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
