apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Values.licensePlate }}-dev
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIp }}
  ipFamilies:
    - IPv4
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  clusterIPs:
    - {{ .Values.service.clusterIp }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
